# syntax=docker/dockerfile:1
FROM node:22-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Vite bakes VITE_* vars into the static bundle at build time -- there is no
# runtime env step for a static SPA, so every backend URL must be known here.
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_OVERVIEW_API_URL
ARG VITE_AWS_ACCOUNTS_API_URL
ARG VITE_GCP_ACCOUNTS_API_URL
ARG VITE_RESOURCES_API_URL
ARG VITE_CUSTOM_DASHBOARDS_API_URL
ARG VITE_COST_MANAGEMENT_API_URL
ARG VITE_COST_OPTIMIZATION_API_URL
ARG VITE_VULNERABILITY_MANAGEMENT_API_URL
ARG VITE_CONTAINERS_API_URL
ARG VITE_MONITORING_API_URL
ARG VITE_ALERTS_API_URL
ARG VITE_REPORTS_API_URL
ARG VITE_USERS_API_URL
ARG VITE_ORGANIZATION_MANAGEMENT_API_URL
ARG VITE_AUTOMATION_API_URL
ARG VITE_SETTINGS_API_URL
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY \
    VITE_OVERVIEW_API_URL=$VITE_OVERVIEW_API_URL \
    VITE_AWS_ACCOUNTS_API_URL=$VITE_AWS_ACCOUNTS_API_URL \
    VITE_GCP_ACCOUNTS_API_URL=$VITE_GCP_ACCOUNTS_API_URL \
    VITE_RESOURCES_API_URL=$VITE_RESOURCES_API_URL \
    VITE_CUSTOM_DASHBOARDS_API_URL=$VITE_CUSTOM_DASHBOARDS_API_URL \
    VITE_COST_MANAGEMENT_API_URL=$VITE_COST_MANAGEMENT_API_URL \
    VITE_COST_OPTIMIZATION_API_URL=$VITE_COST_OPTIMIZATION_API_URL \
    VITE_VULNERABILITY_MANAGEMENT_API_URL=$VITE_VULNERABILITY_MANAGEMENT_API_URL \
    VITE_CONTAINERS_API_URL=$VITE_CONTAINERS_API_URL \
    VITE_MONITORING_API_URL=$VITE_MONITORING_API_URL \
    VITE_ALERTS_API_URL=$VITE_ALERTS_API_URL \
    VITE_REPORTS_API_URL=$VITE_REPORTS_API_URL \
    VITE_USERS_API_URL=$VITE_USERS_API_URL \
    VITE_ORGANIZATION_MANAGEMENT_API_URL=$VITE_ORGANIZATION_MANAGEMENT_API_URL \
    VITE_AUTOMATION_API_URL=$VITE_AUTOMATION_API_URL \
    VITE_SETTINGS_API_URL=$VITE_SETTINGS_API_URL
RUN npm run build

FROM node:22-slim
WORKDIR /app
RUN npm install -g serve@14
COPY --from=build /app/dist ./dist
EXPOSE 8080
# -s = SPA mode (rewrite all unmatched paths to index.html, matching the
# original wrangler.jsonc's not_found_handling: single-page-application)
CMD ["sh", "-c", "serve -s dist -l ${PORT:-8080}"]
